### ISSUE TITLE
LoadPrinterPaperSizes load incorrect sizes

### ISSUE THREAD

**Issue by IncubusRK** [madewokherd/wine-mono#127]
When try to get PrinterSettings.PaperSizes for any available printer, got incorrect sizes (Height and Width).
Like this:
```
    {
        "Height": 167118603,
        "Kind": 9,
        "PaperName": "A4",
        "RawKind": 9,
        "Width": 236551388
    },
```
Perhaps the problem has the same roots as #120 
I test wine 6.15 and got correct PaperSizes. May be LibcupsNative need some changes?
PS. All test was made in 64-bit version of wine

**Comment by madewokherd** [comment]
If this changes based on Wine version and not Wine Mono version (you can install newer Wine Mono on older Wine), it's probably a Wine regression.

**Comment by madewokherd** [comment]
Could you share your test code for this? Then we can see if 32-bit vs 64-bit matters, and which project has the regression. If Wine Mono regressed, it's probably something to do with the code import. If Wine regressed, and 32-bit shows the same problem, it should be possible to bisect that.

**Comment by IncubusRK** [comment]
You may be right, but as far as I understand, wine-mono call CUPS function directly to get paper sizes from ppd. It may be necessary to make changes the LibcupsNative.cs to reflect the last changes in wine

**Comment by madewokherd** [comment]
No, it doesn't. I can categorically state that wine-mono doesn't interact directly with any host libraries. You're probably looking at code that's only used on Unix or in regular Mono.

**Comment by madewokherd** [comment]
That particular .cs file isn't referenced in the build at all. It's probably only used by the Linux version of .NET Core.

**Comment by madewokherd** [comment]
I guess the way we pull code selectively from so many different sources is a source of confusion. Probably the easiest way to figure out what code is actually being used is to examine the dlls (usually in lib/mono/gac) using ILSpy (https://github.com/icsharpcode/AvaloniaILSpy has a Linux build).

**Comment by IncubusRK** [comment]
> No, it doesn't. I can categorically state that wine-mono doesn't interact directly with any host libraries. You're probably looking at code that's only used on Unix or in regular Mono.
Unfortunately, the source code is confused, but you are right.
I create native test sample and make error report https://bugs.winehq.org/show_bug.cgi?id=52132
