### ISSUE TITLE
System.ArgumentException: Propagation flags need inheritance flags.

### ISSUE THREAD

**Issue by DrewRidley** [madewokherd/wine-mono#156]
There seems to be a bug with wine-mono which is triggering an argument exception under `CommonACL.cs`.
This can be seen here,

https://github.com/mono/mono/blob/main/mcs/class/corlib/System.Security.AccessControl/CommonAcl.cs#L416

When trying to run a program that behaves normally under Windows, I get the following error under wine. I am unfamiliar with how ACL works within Windows, let alone wine, so I am uncertain how much help I can be.

I created a corresponding issue upstream [here](https://bugs.winehq.org/show_bug.cgi?id=53904).

Help would be much appreciated.

**Comment by madewokherd** [comment]
We don't need to track this in two different places, Winehq is fine.
