### ISSUE TITLE
Using/proting parts from Uno Platform?

### ISSUE THREAD

**Issue by Fox2Code** [madewokherd/wine-mono#159]
Would be a shame to duplicate parts that have already been done somewhere else!

Project website: https://platform.uno/
Project GitHub: https://github.com/unoplatform/uno

I found it while [trying to search how to run UWP apps on Windows 7](https://stackoverflow.com/questions/34059267/can-uwp-apps-be-ported-to-windows-7)

Also by checking Uno Platform migration guide they said this repo contain some cross platform UWP apis:
- https://github.com/CommunityToolkit/WindowsCommunityToolkit

Even if it end up to nothing, I think it is still worth it to share it there.

**Comment by madewokherd** [comment]
That's cool but UWP is outside the scope of Wine Mono. The C++ APIs are being worked on in Wine itself, and the managed wrappers should be somewhere else so that they can also be used with native .NET Framework.

**Comment by madewokherd** [comment]
The .NET wrappers (which from my limited understanding is in a weird format and not really C# code) can and should exist outside of Wine Mono. They may need to be generated by widl and shipped with Wine itself, or as part of another add-on package.

I did forget that Wine Mono itself will need special support for the wrappers to work, but the rest of it should be done in other parts of Wine. That special support will need to be done in the mono runtime itself, so I doubt Uno would be relevant.

There will be a place in Wine for everything that's needed, but I feel that Wine Mono isn't the right place for the vast majority of the work.
