### ISSUE TITLE
hidpi support

### ISSUE THREAD

**Issue by BloodyIron** [madewokherd/wine-mono#166]
I'm on a hidpi device, Microsoft Surface Pro 9, with 2880x1920 as the resolution. Mono Installer is effectively impossible to read, but I'm pretty sure I clicked on the install button.

Over time more and more hidpi devices will encounter this problem, so this is a bug/feature report getting ahead of this $futureProblem.

Mono should have hidpi support added, can we please add this to some sort of pipeline/planning? :) thanks!

**Comment by madewokherd** [comment]
The installer component you're referring to isn't part of Wine Mono. It's part of Wine's appwiz.cpl, and AFAIK that correctly scales with DPI, but Wine's DPI setting isn't automatically adjusted to match the host desktop. I think you want this bug: https://bugs.winehq.org/show_bug.cgi?id=4045

**Comment by BloodyIron** [comment]
@madewokherd roger that! I've posted in that thread, thanks! :)
