### ISSUE TITLE
[Question] Use .Net Core instead of Mono 

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [madewokherd/wine-mono#187]
Have some wine plans for replacing mono for using .net core?

**Comment by madewokherd** [comment]
No. .NET Core is not designed to be ABI-compatible with .NET Framework, which makes it less useful for replacing .NET Framework. Individual components may be pulled in if they're found to be useful, and some have been.

**Comment by EliasTheGrandMasterOfMistakes** [comment]
> No. .NET Core is not designed to be ABI-compatible with .NET Framework, which makes it less useful for replacing .NET Framework. Individual components may be pulled in if they're found to be useful, and some have been.

thank you
