### ISSUE TITLE
Using the old .NET 4.x WinForms graphics

### ISSUE THREAD

**Issue by theuserbl** [madewokherd/wine-mono#190]
The actual graphics are the new one, which Microsoft added April, 26th, 2019:
https://github.com/madewokherd/winforms/tree/d846549f0e5effe8f8f7d2a64e91746608b6a934/src/System.Windows.Forms/src/Resources/System/Windows/Forms
Thats the typical .NET Core / .NET 5.x graphcis. They are mostly colorless, only black and white. Microsoft says they are "modern".
Here for example the new standard icon for a Windows-Forms-Program:
https://raw.githubusercontent.com/madewokherd/winforms/d846549f0e5effe8f8f7d2a64e91746608b6a934/src/System.Windows.Forms/src/Resources/System/Windows/Forms/wfc.ico

But the old colorful graphics you can find at:
https://github.com/dotnet/winforms/tree/06dc5e3bdfab68d88aaf445fd9e7562f28d05fae/src/System.Windows.Forms/src/Resources/System/Windows/Forms
Thats the graphics of Windows Forms of .NET 4.x.
For comparision, here the default old icon:
https://raw.githubusercontent.com/dotnet/winforms/06dc5e3bdfab68d88aaf445fd9e7562f28d05fae/src/System.Windows.Forms/src/Resources/System/Windows/Forms/wfc.ico

So please use for WinForms in WineMono the old icons amd graphics.

**Comment by madewokherd** [comment]
Patches would be appreciated but I'll add this to my todo list.

**Comment by madewokherd** [comment]
This is looking like a complicated change to revert.

**Comment by madewokherd** [comment]
Well, it eventually built and didn't cause any problems with any of my test cases, so I guess we'll see how it shakes out.
