### ISSUE TITLE
Question: Rationale for not providing a Steam Linux Runtime release artifact

### ISSUE THREAD

**Issue by R1kaB3rN** [madewokherd/wine-mono#204]
In Proton's Makefile, [currently wine-mono is fetched from a tarball](https://github.com/ValveSoftware/Proton/blob/d5207fdbd0fc664f575bd5cee682ca4858696319/Makefile.in#L1054) that contains the pre-built version compiled against libraries in Github's ubuntu-22.04 runner. The same is true for other components such as xalia and Gecko. Modern Proton versions (Proton 7+) are intended to be used within a container runtime, so it follows that all of its components are compiled against the libraries in that runtime. Compiling against the Steam Linux Runtime should be relatively simple as there are images available. [See the DXVK Github Action workflow for details](https://github.com/doitsujin/dxvk/blob/1eb0c687a6748d8268dd84f466a1378de4fb3c10/.github/workflows/artifacts.yml#L37). 

Am I missing something?

**Comment by madewokherd** [comment]
Both packages contain only Win32 code, so they wouldn't link to libraries in the Steam Linux Runtime.

That said, there are other reasons to integrate the build with Proton. I'd like to do that for Xalia at least (it appears to be feasible to build on Linux with dotnet), just haven't yet found the time to work on it. For Wine Mono I'm less certain, simply because the build process takes so much time.

**Comment by R1kaB3rN** [comment]
I don't think build times should be a big concern as wine-mono is currently being built in parallel across its platforms in its CI. Like DXVK, we can just add another workflow then simply update Proton's Makefile to fetch the Steam Linux Runtime artifact instead.

What do you think?

**Comment by madewokherd** [comment]
If we produced a different artifact in Wine Mono's CI, there would be no practical difference for anyone (other than using more CI resources), because it's all Win32 code, no Linux code.

**Comment by R1kaB3rN** [comment]
The artifact would be built using the same toolchain and environment as other Proton's components rather than the ones provided by Ubuntu 22.04's. If you believe that there are no benefits to that, I'll close this.
