### ISSUE TITLE
Provide stub libraries missing routines.

### ISSUE THREAD

**Issue by Ruedii** [madewokherd/wine-mono#22]
Much like wine provides stubs for all known missing routines, wine-mono should attempt to do the same.

While this won't fix all the problems related to missing routines, it will certainly fix a few of them, and allow debugging of many more problems.

Also, if there was a simple method and instructions to install mono versions of the missing libraries in the mono directory, it would be very helpful.  

If it could be done automatically, this would be even better.  However, unless automated installation can be implemented effortlessly, it's probably not worth it.

**Comment by Ruedii** [comment]
As a note, some stubs (such as in UI libraries) should simply create a stub that passes on size parameters to a placeholder box.

**Comment by madewokherd** [comment]
I don't understand what you're suggesting. We can add stubs where needed, but even on Wine it's not something we do proactively.
