### ISSUE TITLE
[Debian] Build fails with error: **Error**: You must have `libtool' installed to compile Mono.

### ISSUE THREAD

**Issue by gamehawk197** [madewokherd/wine-mono#24]
I have the latest version of libtools, but the script throws up this error anyway. I have all of mono's dependencies.

**Comment by madewokherd** [comment]
That's odd. Is libtool in your PATH? If not, you can set the LIBTOOL environment variable to its path and filename.

**Comment by ThiasJ** [comment]
I ran into the same issue! on Debian (and maybe ubuntu) it seems you have to install the package "libtool-bin"

source: http://linux-doku.de/blog/mono-auf-ubuntu-kompilieren [german]

**Comment by shaheeniu** [comment]
Try this to fix.
sudo apt-get install libtool-bin

**Comment by Julian10852Hack** [comment]
@shaheeniu thank you, i had very time searching an solutions for this problem

**Comment by dooteo** [comment]
@shaheeniu Great! Thats solves the issue! Thank you!

**Comment by kYroL01** [comment]
This fix the issue. This thread must be closed

**Comment by edidada** [comment]
@shaheeniu get it thanks!

**Comment by guillaume-a** [comment]
@shaheeniu years after, you saved my day.

**Comment by helmet1980** [comment]
It works!

**Comment by CreeperDude372** [comment]
@shaheeniu  Thank you so much! I've been looking for a solution for 3 months.
