### ISSUE TITLE
Bad Exe format

### ISSUE THREAD

**Issue by gerroon** [madewokherd/wine-mono#25]
I am trying to install these mono packages but I got errors both or 0.0.8 and the one below

wine: Bad EXE format for .wine-mono-4.5.6.msi

I am on Debian Jessie 64 Wine wine-1.6.2 (I belive 32 bit version)

**Comment by madewokherd** [comment]
You need to use 'msiexec' to install msi files. http://wiki.winehq.org/msiexec

**Comment by gerroon** [comment]
thanks
