### ISSUE TITLE
Version matrix wine / wine-mono

### ISSUE THREAD

**Issue by suchja** [madewokherd/wine-mono#26]
Trying to find out which wine-mono to use with which wine version. I'll add a version matrix to the [wine mono page on WineWiki](http://wiki.winehq.org/Mono-Wine_bridge). After looking to all release announcements I still have some questions. Here is what I have so far:

||wine-1.5.3 - wine-1.5.15 ||<width="10px"> || wine-mono-0.0.4.msi ||
||wine-1.5.16 - wine-1.**?** || || wine-mono-0.0.8.msi ||
||**wine-? - wine-?** || || wine-mono-4.5.0.msi ||
||wine-1.7.8 - wine-1.7.31 || || wine-mono-4.5.2.msi ||
||wine-1.7.32 - wine-1.7.37 || || wine-mono-4.5.4.msi ||
||wine-1.7.38 - current || || wine-mono-4.5.6.msi ||

Does somebody know until which version wine-mono-0.0.8 was used? I know wine-1.6.2 still uses it.
Also I could not find any reference to wine-mono-4.5.0 at all. Any ideas in which wine version it was used?

**Comment by madewokherd** [comment]
You can always check the history of https://source.winehq.org/source/dlls/appwiz.cpl/addons.c to see what a given Wine version will install.

However, that's not necessarily the "best" version to use. For instance, 4.5.6 was a small change to fix a regression in 4.5.4, and is what I'd recommend using back to wine 1.7.32 at least (assuming  you have a reason to use those old wine releases). But figuring that out exactly would mean digging through Wine's history which could lead to mistakes and probably isn't worth the effort.

**Comment by suchja** [comment]
I see. The problem I had was that I tried to use wine in a headless environment and wanted to get rid of wine asking whether it shall download wine-mono and gecko. Thus my idea was to supply a version, which can be used. Unfortunately wine did not like the newest or "any" version of those add ons. Thus it took me quite some time to figure out exactly which version of wine-mono I had to supply.

The [wine gecko page](http://wiki.winehq.org/Gecko) shows a pretty good overview about the versions. Thus I thought we could supply something similar. However, if you say there is no such strickt dependency, then how can I tell wine to use another version without user interaction?

One more question. Is there a way to find out whether wine believes wine-mono and gecko are properly (in the correct version) installed?

**Comment by madewokherd** [comment]
OK, it sounds like you were trying to ask "which version will prevent the dialog on startup", and I was trying to answer "which version is the best one to use". The version Wine will look for, and the best one for your purposes, is the one specified in https://source.winehq.org/source/dlls/appwiz.cpl/addons.c, where it says "#define MONO_VERSION". You can use the Version drop-down on that page to check what was in each Wine release.

If you're not running .NET applications, you can prevent the install of wine-mono entirely by setting WINEDLLOVERRIDES=mscoree=d when creating or updating the prefix. If you want to prevent the install of both Mono and Gecko, you can use WINEDLLOVERRIDES=mscoree,mshtml=d

The easiest way I can think of to test whether the correct versions are installed is to do a prefix update (wineboot -u).

To use a different Mono version, you would have to uninstall the current one (using the wine uninstaller command on the Mono wiki page) and install a different one using msiexec. This doesn't help you prevent user interactions, though.
