### ISSUE TITLE
System.Xml.dll cannot be found 

### ISSUE THREAD

**Issue by xsmyqf** [madewokherd/wine-mono#27]
Makefile:812: warning: overriding recipe for target 'mod'
Makefile:792: warning: ignoring old recipe for target 'mod'
make[2]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/scripts'
Makefile:812: warning: overriding recipe for target 'mod'
Makefile:792: warning: ignoring old recipe for target 'mod'
 /bin/mkdir -p '/home/xieshuai/source/wine-mono/build-cross-cli-install/bin'
 /usr/bin/install -c makecert sn al ilasm gacutil mkbundle monop resgen wsdl al2 gacutil2 monop2 resgen2 wsdl2 mono-service mono-service2 nunit-console nunit-console2 nunit-console4 mono-find-provides mono-find-requires mdoc-assemble mdoc-export-html mdoc-export-msxdoc mdoc-update mdoc-validate ../../mono/scripts/mdassembler ../../mono/scripts/mdvalidater ../../mono/scripts/monodocer ../../mono/scripts/monodocs2html ../../mono/scripts/monodocs2slashdoc ../../mono/scripts/mono-test-install peverify mcs ../../mono/scripts/mono-heapviz mono-configuration-crypto disco dtd2xsd dtd2rng installvst '/home/xieshuai/source/wine-mono/build-cross-cli-install/bin'
 /usr/bin/install -c genxs macpack mdoc mono-cil-strip prj2make soapsuds caspol cert-sync cert2spc certmgr chktrust crlupdate csharp httpcfg lc mconfig mod monolinker mono-api-info mono-shlib-cop mozroots permview pdb2mdb xsd mono-xmltool setreg secutil signcode sgen sqlmetal sqlsharp svcutil ccrewrite cccheck mdbrebase ikdasm mono-symbolicate dmcs xbuild '/home/xieshuai/source/wine-mono/build-cross-cli-install/bin'
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/scripts'
make[1]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/scripts'
Making install in man
make[1]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/man'
make[2]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/man'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/xieshuai/source/wine-mono/build-cross-cli-install/share/man/man1'
 /usr/bin/install -c -m 644 ../../mono/man/al.1 ../../mono/man/cert2spc.1 ../../mono/man/certmgr.1 ../../mono/man/chktrust.1 ../../mono/man/cilc.1 ../../mono/man/crlupdate.1 ../../mono/man/csharp.1 ../../mono/man/disco.1 ../../mono/man/dtd2xsd.1 ../../mono/man/gacutil.1 ../../mono/man/genxs.1 ../../mono/man/httpcfg.1 ../../mono/man/ilasm.1 ../../mono/man/lc.1 ../../mono/man/macpack.1 ../../mono/man/makecert.1 ../../mono/man/mconfig.1 ../../mono/man/mcs.1 ../../mono/man/mdassembler.1 ../../mono/man/mdoc.1 ../../mono/man/mdoc-assemble.1 ../../mono/man/mdoc-export-html.1 ../../mono/man/mdoc-export-msxdoc.1 ../../mono/man/mdoc-update.1 ../../mono/man/mdoc-validate.1 ../../mono/man/mdvalidater.1 ../../mono/man/mkbundle.1 ../../mono/man/mono.1 ../../mono/man/mprof-report.1 ../../mono/man/mono-cil-strip.1 ../../mono/man/monodocer.1 ../../mono/man/monodocs2html.1 ../../mono/man/monolinker.1 ../../mono/man/monop.1 ../../mono/man/mono-api-info.1 ../../mono/man/mono-service.1 ../../mono/man/mono-shlib-cop.1 ../../mono/man/mono-xmltool.1 ../../mono/man/mozroots.1 ../../mono/man/pdb2mdb.1 '/home/xieshuai/source/wine-mono/build-cross-cli-install/share/man/man1'
 /usr/bin/install -c -m 644 ../../mono/man/permview.1 ../../mono/man/prj2make.1 ../../mono/man/resgen.1 ../../mono/man/secutil.1 ../../mono/man/setreg.1 ../../mono/man/sgen.1 ../../mono/man/signcode.1 ../../mono/man/sn.1 ../../mono/man/soapsuds.1 ../../mono/man/sqlsharp.1 ../../mono/man/wsdl.1 ../../mono/man/xbuild.1 ../../mono/man/xsd.1 ../../mono/man/mono-configuration-crypto.1 ../../mono/man/ccrewrite.1 ../../mono/man/cccheck.1 ../../mono/man/mono-symbolicate.1 '/home/xieshuai/source/wine-mono/build-cross-cli-install/share/man/man1'
 /bin/mkdir -p '/home/xieshuai/source/wine-mono/build-cross-cli-install/share/man/man5'
 /usr/bin/install -c -m 644 ../../mono/man/mdoc.5 ../../mono/man/mono-config.5 '/home/xieshuai/source/wine-mono/build-cross-cli-install/share/man/man5'
make[2]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/man'
make[1]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/man'
Making install in samples
make[1]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/samples'
make[2]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/samples'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/samples'
make[1]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/samples'
Making install in msvc
make[1]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/msvc'
make[2]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/msvc'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/msvc'
make[1]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/msvc'
Making install in acceptance-tests
make[1]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/acceptance-tests'
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
make[2]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli/acceptance-tests'
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/acceptance-tests'
make[1]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli/acceptance-tests'
make[1]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli'
make[2]: Entering directory '/home/xieshuai/source/wine-mono/build-cross-cli'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli'
make[1]: Leaving directory '/home/xieshuai/source/wine-mono/build-cross-cli'
mono-basic 2.11 module configured to use prefix=/home/xieshuai/source/wine-mono/build-cross-cli-install
make[1]: Entering directory '/home/xieshuai/source/wine-mono/mono-basic/tools'
make[2]: Entering directory '/home/xieshuai/source/wine-mono/mono-basic/tools/extract-source'
Creating ../../build/deps/net_4_0_extract-source.exe.makefrag ...
make all-local
make[3]: Entering directory '/home/xieshuai/source/wine-mono/mono-basic/tools/extract-source'
MONO_PATH="../../class/lib/bootstrap:$MONO_PATH" mono  --debug ../../class/lib/bootstrap/vbnc.exe   /sdkpath:/home/xieshuai/source/wine-mono/build-cross-cli-install/lib/mono/4.0/ -debug -r:System.Xml.dll -noconfig -define:_MYTYPE=\"Empty\" /novbruntimeref /r:../../class/lib/bootstrap/Microsoft.VisualBasic.dll -target:exe -out:extract-source.exe   @extract-source.exe.sources
Symbol file /home/xieshuai/source/wine-mono/mono-basic/class/lib/bootstrap/vbnc.exe.mdb doesn't match image /home/xieshuai/source/wine-mono/mono-basic/class/lib/bootstrap/vbnc.exe
Visual Basic.Net Compiler version 0.0.0.5943 (Mono 2.11 - master/234d628)
Copyright (C) 2004-2010 Rolf Bjarne Kvinge. All rights reserved.

vbnc: Command line : error VBNC2017: The library 'System.Xml.dll' could not be found.
There were 1 errors and 0 warnings.
Compilation took 00:00:00.2001460
../../build/executable.make:81: recipe for target 'extract-source.exe' failed
make[3]: **\* [extract-source.exe] Error 1
make[3]: Leaving directory '/home/xieshuai/source/wine-mono/mono-basic/tools/extract-source'
../../build/rules.make:123: recipe for target 'do-all' failed
make[2]: **\* [do-all] Error 2
make[2]: Leaving directory '/home/xieshuai/source/wine-mono/mono-basic/tools/extract-source'
../build/rules.make:135: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/xieshuai/source/wine-mono/mono-basic/tools'
build/rules.make:135: recipe for target 'all-recursive' failed

hi,when I run 'build-winemono.sh',the error occured.I have no idea with this,can you help me ?

**Comment by madewokherd** [comment]
My guess is something went wrong earlier in the process.

**Comment by wizonesolutions** [comment]
Same here. The amount of `python` errors looks weird, but I don't even know where to start troubleshooting. Building on Ubuntu 15.10 (next attempt will probably be on 16.04 though).

````
Making install in acceptance-tests
make[1]: Entering directory '/home/kevin/src/wine-mono/build-cross-cli/acceptance-tests'
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
make[2]: Entering directory '/home/kevin/src/wine-mono/build-cross-cli/acceptance-tests'
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
python: can't open file 'versions.py': [Errno 2] No such file or directory
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/kevin/src/wine-mono/build-cross-cli/acceptance-tests'
make[1]: Leaving directory '/home/kevin/src/wine-mono/build-cross-cli/acceptance-tests'
make[1]: Entering directory '/home/kevin/src/wine-mono/build-cross-cli'
make[2]: Entering directory '/home/kevin/src/wine-mono/build-cross-cli'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/kevin/src/wine-mono/build-cross-cli'
make[1]: Leaving directory '/home/kevin/src/wine-mono/build-cross-cli'
mono-basic 2.11 module configured to use prefix=/home/kevin/src/wine-mono/build-cross-cli-install
make[1]: Entering directory '/home/kevin/src/wine-mono/mono-basic/tools'
make[2]: Entering directory '/home/kevin/src/wine-mono/mono-basic/tools/extract-source'
Creating ../../build/deps/net_4_0_extract-source.exe.makefrag ...
make all-local
make[3]: Entering directory '/home/kevin/src/wine-mono/mono-basic/tools/extract-source'
MONO_PATH="../../class/lib/bootstrap:$MONO_PATH" mono  --debug ../../class/lib/bootstrap/vbnc.exe   /sdkpath:/home/kevin/src/wine-mono/build-cross-cli-install/lib/mono/4.0/ -debug -r:System.Xml.dll -noconfig -define:_MYTYPE=\"Empty\" /novbruntimeref /r:../../class/lib/bootstrap/Microsoft.VisualBasic.dll -target:exe -out:extract-source.exe   @extract-source.exe.sources
Symbol file /home/kevin/src/wine-mono/mono-basic/class/lib/bootstrap/vbnc.exe.mdb doesn't match image /home/kevin/src/wine-mono/mono-basic/class/lib/bootstrap/vbnc.exe
Visual Basic.Net Compiler version 0.0.0.5943 (Mono 2.11 - master/234d628)
Copyright (C) 2004-2010 Rolf Bjarne Kvinge. All rights reserved.

vbnc: Command line : error VBNC2017: The library 'System.Xml.dll' could not be found.
There were 1 errors and 0 warnings.
Compilation took 00:00:00.4187070
../../build/executable.make:81: recipe for target 'extract-source.exe' failed
make[3]: *** [extract-source.exe] Error 1
make[3]: Leaving directory '/home/kevin/src/wine-mono/mono-basic/tools/extract-source'
../../build/rules.make:123: recipe for target 'do-all' failed
make[2]: *** [do-all] Error 2
make[2]: Leaving directory '/home/kevin/src/wine-mono/mono-basic/tools/extract-source'
../build/rules.make:135: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/kevin/src/wine-mono/mono-basic/tools'
build/rules.make:135: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
````

**Comment by HinTak** [comment]
well, where is python trying to open 'versions.py' ? I suspect you have something strange in your python execution environment - e.g. a symlink of that name that points nowhere. strace for the open system call, or find  home/kevin/src/wine-mono/ -name 'versions.py' ? or look into your pythonpath?

**Comment by madewokherd** [comment]
I encountered this error while working on the 4.7.0 release, and I concluded that it was because the mono-basic submodule was very outdated. I have updated mono-basic from upstream, hopefully that will help.

**Comment by madewokherd** [comment]
No update on whether the fix helped, closing.
