### ISSUE TITLE
Certificate validation doesn't work on OSX-wine.

### ISSUE THREAD

**Issue by rvuistin** [madewokherd/wine-mono#28]
See the proposed patch in the [mono repo](https://github.com/mono/mono/pull/3798)

**Comment by madewokherd** [comment]
Thanks for telling me about this. I applied the patch to the 4.6 branch.

We should really be pulling the certs from crypt32 stores, there should be no need to run a tool like mozroots. But hopefully this will make things easier for you until then, and maybe it will still be needed when we have a better solution.

**Comment by rvuistin** [comment]
@madewokherd 

For your information, the [patch in the mono repo](https://github.com/mono/mono/commit/cd8e84c1f1dede8d6b7670957834d0f14d72c959) has finally been merged. The code has changed slightly since your merge into the 4.6 branch. I let you sync with the upstream

**Comment by madewokherd** [comment]
Thanks. I don't think we need to do anything in the 4.6 branch, because only the behavior on Windows/Wine really matters. When we branch for 4.7, the merged version will already be there.
