### ISSUE TITLE
add MonoDX  in to project

### ISSUE THREAD

**Issue by Eignar17** [madewokherd/wine-mono#30]
https://github.com/alesliehughes/monoDX

is good idea @madewokherd ?

**Comment by madewokherd** [comment]
Sure, but I assume the original assemblies have a strongname and we'll have to figure out signing for these.

**Comment by Eignar17** [comment]
is good your wine-mono +monoDX my dreams is reality

**Comment by alesliehughes** [comment]
This was developed originally for Gray Matter demo
https://bugs.winehq.org/show_bug.cgi?id=34045

**Comment by rbernon** [comment]
I actually hacked monoDX a bit for L.A.Noire launcher, and got it to the point where it's working enough for what it's doing with it. I was afraid it would need more but it looks like it's only interested in adapters and display modes and some simple device caps.

I forked monoDX in https://github.com/rbernon/monoDX and integrated it with wine-mono in https://github.com/rbernon/wine-mono/tree/monodx

**Comment by madewokherd** [comment]
I'm unsure how I should handle this now. @alesliehughes should I treat you as an upstream so you have the opportunity to review contributions like @rbernon's changes? Or should I just pull things in that seem OK to me?

**Comment by alesliehughes** [comment]
I've alreaded pull that code into my tree.

**Comment by madewokherd** [comment]
Well in that case @rbernon is the integration into wine-mono in a state where I should review it and possibly merge it in?

**Comment by rbernon** [comment]
Yeah I think it should be usable. I'm unsure however about how this will behave if the native DLL is already there or installed on top of it. We should probably prefer it instead of the builtin monoDX to avoid regressions (as most things are still unimplemented).

**Comment by madewokherd** [comment]
Assemblies installed in the windows GAC will take priority over the ones we ship, unless configured otherwise by WINE_MONO_OVERRIDES, the AsmOverrides registry key, or the hard-coded default for XNA. So that shouldn't be a problem.

**Comment by madewokherd** [comment]
Pushed as https://github.com/madewokherd/wine-mono/commit/c71bdb94713c92cf58a38d6ef81417edc6f85fd2

I changed the submodule reference to my own fork, removed a reference to System.Xaml, and removed some unused things from monodx.make.

I'm unsure about this approach of using LoadLibrary to load d3d9 instead of just linking it normally, but it got accepted upstream so 🤷‍♀️

**Comment by rbernon** [comment]
Thanks!

> I'm unsure about this approach of using LoadLibrary to load d3d9 instead of just linking it normally, but it got accepted upstream so

I initially thought it could be a soft requirement to load d3d9, as it was previously not using any native bridge and I wasn't sure what monoDX was used for, but then it probably doesn't make much sense now.

**Comment by rbernon** [comment]
I think there's one more thing that may be missing but I don't know how to do it. L.A.Noire checks for `C:/Windows/Microsoft.NET/DirectX for Managed Code` directory presence before trying to load the assembly. I've added the directory creation to support.make, but I don't think it's getting created in all cases. I think the assembly is supposed to be there, but that could conflict with native installs and we probably only want the folder.

**Comment by madewokherd** [comment]
Are you sure you installed the support msi? It won't happen automatically in a lot of cases during development.

**Comment by rbernon** [comment]
Ah, indeed I've not been using the msi so it's possible.
