### ISSUE TITLE
Using .NET Framework Assemblies with Wine-Mono runtime

### ISSUE THREAD

**Issue by hadi77ir** [madewokherd/wine-mono#31]
I want to run WPF applications on Wine, but failed to install and get .NET Framework 4.5 working on my wine prefix. So I thought that it maybe possible to use assemblies provided by Microsoft instead Wine-Mono ones.
Is it technically possible? (since original Microsoft assemblies are written in C++/CLI and Mono is written mainly in C#)

**Comment by madewokherd** [comment]
In theory, it could work, as long as the Microsoft implementation doesn't rely on reflection/internals of the rest of the class libraries. C++/CLI can be supported by Wine Mono. In practice, it's probably easier to get .NET 4.5 working.
