### ISSUE TITLE
Compiling from source leads to missing libiconv-2.dll

### ISSUE THREAD

**Issue by DarkShadow44** [madewokherd/wine-mono#39]
```
0009:err:module:import_dll Library libiconv-2.dll (which is needed by L"C:\\windows\\mono\\mono-2.0\\bin\\libmono-2.0-x86.dll") not found
0009:err:mscoree:load_mono Could not load Mono into this process
```

Not sure what's wrong here, but when I compile from source I always need to copy libiconv-2.dll into current working directory, else wine can't load mono into the process.
This is not the case with pre-compiled wine-mono though.

**Comment by madewokherd** [comment]
Maybe your mingw has extra libraries? If so, we should figure be able to pass some option to Mono's configure to prevent it from using them.

The pre-compiled package is made using a VM created by the included vagrant script.

**Comment by DarkShadow44** [comment]
Well, I needed to install https://aur.archlinux.org/packages/mingw-w64-libiconv/ for it to compile in the first place, not sure.

**Comment by madewokherd** [comment]
Maybe on Ubuntu it uses a static lib?

**Comment by DarkShadow44** [comment]
Possibly. I also have a static lib in that package, but I don't know how to tell it to use that instead.

**Comment by HinTak** [comment]
It looks like archlinux provides mingw-w32-libiconv-static . You need to install that, and and some compiler switch (-static, possibly).

**Comment by DarkShadow44** [comment]
Arch doesn't provide mingw-w32-libiconv-static, but mingw-w32-libiconv which includes a static .a library.

For the x64 build, I tried adding
`LDFLAGS="-L/usr/x86_64-w64-mingw32/lib/ -l:libiconv.a"`

But then I only get errors, it doesn't even create libmono-2.0:
```
*** Warning: Trying to link with static lib archive /usr/x86_64-w64-mingw32/lib//libiconv.dll.a.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because the file extensions .a of this argument makes me believe
*** that it is just a static archive that I should not use here.

*** Warning: linker path does not have real file for library -l:libiconv.a.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with lib:libiconv.a but no candidates were found. (...for file magic test)

*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.
```

Any idea? Appearently libtool doesn't allow linking static libs into a shared DLL.

**Comment by madewokherd** [comment]
This has gone beyond my knowledge. I have a feeling you might need to give the full path with no switches to link to a static library. You might also want to double-check that what you have is really a static lib and not a libtool stub.

**Comment by HinTak** [comment]
The message tells you exactly the problem - Your LDFLAGS is wrong - you should do `... -liconv` . It looks as if you have a libiconv.dll.a around. Try to move it elsewhere/rename temporarily. The dynamic one always takes priority when present.

**Comment by DarkShadow44** [comment]
That doesn't help:

```
*** Warning: linker path does not have real file for library -liconv.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libiconv and none of the candidates passed a file format test
*** using a file magic. Last file checked: /usr/x86_64-w64-mingw32/lib/libiconv.a
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.
```
It's finding the static library, and complaining.

Also, I have both static and dynamic, that's why I explicitly specified the static library.

**Comment by HinTak** [comment]
The one that is real on fedora is 22k, the dll.a stub is 6k. The 64-bit windows one is 26k.

I just noticed what went wrong in yours - again it is in the message: you are using the 64-bit windows one! Instead of `/usr/x86_64-w64-mingw32/lib/libiconv.a`, you want the one in `/usr/i686-w64-mingw32/...`! At least on fedora, I have both of those at the two locations.

**Comment by DarkShadow44** [comment]
But I'm compiling 64bit mono, why would I need a 32bit library for that?

**Comment by madewokherd** [comment]
The build script compiles both 64-bit and 32-bit mono, so you need libraries for both.

**Comment by DarkShadow44** [comment]
I have both. But it already fails when trying to build the x64 bit version, so I just focused on getting that to work.

**Comment by HinTak** [comment]
Does your libiconv depends on something else? On mine they don't; but never say never

**Comment by DarkShadow44** [comment]
Can't reproduce this anymore, let's close this.
