### ISSUE TITLE
64-bit runtime support

### ISSUE THREAD

**Issue by HinTak** [madewokherd/wine-mono#40]
Recently I have had the need of looking at a p/invoke problem on 64-bit windows, and had some success with running win64 mono 5.14 on 64-bit wine.

I see that running the dotnet app on 64-bit wine , without win64 mono, pinvokes the 32-bit libraries. So wine-mono is still exclusively 32-bit only.

Any plan to port a more recent mono and enable 64-bit wine-mono ? We had some discussion about this a few years ago on wine-devel when 64-bit mono was a bit young. Now it seems usable.

**Comment by madewokherd** [comment]
64-bit wine-mono is included, and 64-bit Wine will run .NET executables with it. However, for pure CLR images, it won't switch from 32-bit to 64-bit, so you get a different result depending on whether you use wine or wine64.

I think this is a Wine bug, and Wine should decide which architecture to use based on the image headers.

Closing for now. Let me know if you still have this issue when using wine64 to start the exe.

**Comment by HinTak** [comment]
Thanks! I'll give it a try after the upgrade. It's been overdue. My .net application detects the runtime and p/invoke the different arch of native libraries.

Assuming it all works out, I'll leave a comment here either way, after testing. (maybe in a week or two). Thanks a lot for the work over the years.

**Comment by HinTak** [comment]
@madewokherd : yes, just confirming that using wine64 to start indeed get .net to p/invoke the 64-bit native libs. 

I remembered a few years ago I asked a similar question on wine-devel, and was told that while wine-mono ships both versions of dll, the 64-bit version was not used. Is the ability to use 64-bit mono (with wine64) recent or I was mistaken to think that the 64-bit mono dll was not used during the earlier period it was provided?

**Comment by madewokherd** [comment]
I think it was added in the last few years, yes.
