### ISSUE TITLE
update to mono 5.14 + for better metadata processing?

### ISSUE THREAD

**Issue by HinTak** [madewokherd/wine-mono#42]
As I found with mixed mode support ( https://github.com/madewokherd/wine-mono/issues/41 ) it seems that mono 5.14+ is significantly better than 5.12 . I think wine-mono's mono dependencies is at 5.9-ish?

**Comment by HinTak** [comment]
Correction - wine-mono seems to be mono 5.2 +

**Comment by madewokherd** [comment]
We just track the main branch, release branches aren't worth it.
