### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by HinTak** [madewokherd/wine-mono#44]
4.7.3 is around for a while - and given a fair number of interesting updates from mono, is a new tagged release out soon?

**Comment by HinTak** [comment]
Sorry to hear that. Is there a release criteria / test suite for it? Or is it worth just tagging a new release and hope for the best? I think there are not much change within wine-mono per se , but plenty inherited from upstream mono.

**Comment by madewokherd** [comment]
It's too late to properly test a new release before code freeze. I have a few sanity checks that I do, but no good test suite.
