### ISSUE TITLE
FNA Integration

### ISSUE THREAD

**Issue by flibitijibibo** [madewokherd/wine-mono#45]
Finally got some time to explore this, and the initial results have been good!

![winemonofnaabi](https://user-images.githubusercontent.com/1396814/52974017-1871e200-338e-11e9-98f5-6c96f369a4ee.png)

Here's how it currently works:

1. With a fresh Wine prefix, run any XNA program
2. It crashes, but hey, the Mono stuff's in there now!
3.
```
git clone --recursive git://github.com/FNA-XNA/FNA.git
git clone git://github.com/FNA-XNA/FNA.NetStub.git
cd FNA/abi
xbuild

cd bin/Debug # Of course, you can also build in Release mode...
cp *.dll $WINEPREFIX/drive_c/windows/mono/mono-2.0/lib/mono/4.5/Facades/
curl -O http://fna.flibitijibibo.com/archive/fnalibs.tar.bz2
tar xvfj fnalibs.tar.bz2 x86
cp x86/* $WINEPREFIX/drive_c/windows/mono/mono-2.0/lib/mono/4.5/Facades/
```

Many XNA games will work just fine with this! However, we still have to abide by the [content compatibility guidelines](https://github.com/FNA-XNA/FNA/wiki/2:-Building-with-FNA#2-about-content-support), meaning WMV, WMA, and xWMA will have to be recompressed and half-pixel offsets will goof things up.

Those rules are something that FNA itself would have to fight with, but the steps listed above could possibly be integrated into wine-mono. Like .NET, we would have to block attempts to install XNA.

**Comment by madewokherd** [comment]
We would also need to build the libraries in fnalibs.tar.bz2, and set up an appropriate dll mapping for them based on architecture.

FNA itself should probably be renamed so the included version doesn't interact with FNA games.

I'm thinking some sort of override system similar to what Wine has for regular dll's might make more sense than preventing the XNA install. It would provide more flexibility in case we get XNA working in the future. I'm not sure how it would work exactly, but it'd probably belong in Wine's mscoree.

**Comment by flibitijibibo** [comment]
Makes sense to me!

For self-building it's fortunately very easy; inside the FNA repo is all the source to every library except for SDL2 and SDL2_image, so not a lot of extra downloading to do. All the fnalibs are currently built with MinGW so a from-source build should be pretty much exactly the same as the "official" binaries with no added fuss.

**Comment by flibitijibibo** [comment]
Added msbuild project files to the ABI folder, so now instead of doing a bunch of separate builds, you can `cd FNA/abi` and `xbuild` to get all the DLLs at once.

**Comment by madewokherd** [comment]
I started on SDL2, but the x86 build keeps linking to libgcc_s_sjlj-1.dll. Did you have to apply any work-arounds for this in your build process.

**Comment by flibitijibibo** [comment]
I believe you have to set LDFLAGS="-static-libgcc" - these scripts should be helpful in getting all the right settings:

http://www.libsdl.org/extras/win32/cross/cross-configure.sh
http://www.libsdl.org/extras/win32/cross/cross-make.sh

**Comment by madewokherd** [comment]
I'm tempted to try to replace the SDL_image dep with standard win32/.NET stuff. I don't like shipping the extra version of libpng/libjpeg.

**Comment by flibitijibibo** [comment]
This may be of interest: https://github.com/FNA-XNA/SDL_image_compact

**Comment by madewokherd** [comment]
Is staticly shipping a different set of image libraries better?

**Comment by flibitijibibo** [comment]
Not sure, this is just the repo that's used for fnalibs. Not sure if any of this would need renaming like FNA.dll.

**Comment by madewokherd** [comment]
When you say fnalibs is build with mingw, is the build system Windows or Linux? I'm learning that cross-compiles are very tricky for cmake at least.

**Comment by flibitijibibo** [comment]
All builds are done with CentOS 7. For CMake I believe you should have `mingw32-cmake` and `mingw64-cmake` available. If the CMake version is too old (like the one in CentOS, at least for MinGW) you'll want to run it with `mingw64-cmake -DCMAKE_C_FLAGS="-std=c99"`.

**Comment by madewokherd** [comment]
There's no such thing on Ubuntu, which I use for the build VM. I'll have to see where that centos package comes from and if any of it can be reused.

**Comment by skitt** [comment]
> There's no such thing on Ubuntu, which I use for the build VM. I'll have to see where that centos package comes from and if any of it can be reused.

The CentOS package comes from [here](https://src.fedoraproject.org/rpms/mingw-filesystem/tree/master) (well, that’s the Fedora version, but it does the same thing). You’d have to adapt [toolchain-mingw32.cmake](https://src.fedoraproject.org/rpms/mingw-filesystem/blob/master/f/toolchain-mingw32.cmake) and [toolchain-mingw64.cmake](https://src.fedoraproject.org/rpms/mingw-filesystem/blob/master/f/toolchain-mingw64.cmake), and use them as

    cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/toolchain-mingw32.cmake ...

Most of the settings should work as-is on Ubuntu with the `mingw-w64` toolchain, for 32- and 64-bit binaries. The one settings which won’t work is `CMAKE_FIND_ROOT_PATH`; I think `/usr/i686-w64-mingw32` and `/usr/x86_64-w64-mingw32` should work, but I’m not 100% sure.

I’m the Debian and Ubuntu MinGW-w64 toolchain maintainer, feel free to ping me with any issues you encounter.

**Comment by madewokherd** [comment]
Hmm, GPL isn't going to be an issue if I want to include some of those files in wine-mono, is it? We need wine-mono binaries to be loadable in-process and distributable with proprietary code.

**Comment by madewokherd** [comment]
I guess if I'm just using it to find the appropriate settings and not copying the files over, there's probably not enough in there to matter.

**Comment by madewokherd** [comment]
Here's a WIP branch with my build changes so far: https://github.com/madewokherd/wine-mono/tree/fna-wip

The cmake build turned out to be pretty simple with the pointers from Stephen. I only needed a couple of settings from the centos package.

I haven't been able to persuade SDL2_image's build system to use my renamed SDL library. I'm thinking an alternate System.Drawing codepath in FNA might be a better use of my time. At least on Wine, we can assume it's available and uses the system libraries for image format support (indirectly through WIC).

What version of MojoSetup should I use for FNA?

**Comment by flibitijibibo** [comment]
If we can use GDI directly instead of using System.Drawing that'll be easier for us to keep - ironically it's easier to maintain single-assembly portability by explicitly _avoiding_ Drawing and using DllImports instead! We only use SDL_image for PNG/JPG loading/saving, but we do use SDL_Surface for some weird stuff that XNA does with surface data. I bet we can use SDL_Surface with GDI bitmaps though, even if it needs a big ol memcpy first. You can `grep SDL_image` in this file and find all of them pretty quickly:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs

For MojoShader we can use this repo, since it's the same one used as a submodule in FNA itself:

https://github.com/FNA-XNA/MojoShader

It's 1:1 with upstream, plus the C# files that FNA uses to access the native library. No matter which one you use (this or the upstream Hg repo) the CMake config should be the same:

```
-DBUILD_SHARED=ON -DPROFILE_D3D=OFF -DPROFILE_BYTECODE=OFF -DPROFILE_ARB1=OFF -DPROFILE_ARB1_NV=OFF -DPROFILE_METAL=OFF -DCOMPILER_SUPPORT=OFF -DFLIP_VIEWPORT=ON -DDEPTH_CLIPPING=ON -DXNA4_VERTEXTEXTURE=ON
```

**Comment by madewokherd** [comment]
Sure, we could use GDI+ or WIC directly with DllImports. Both have C API's.

I didn't realize FNA had submodules for some of the dependencies. I should probably use those directly.

**Comment by flibitijibibo** [comment]
Yep, our submodules contain the source to everything except SDL and SDL_image, since those are Hg repos and sometimes have Secret Console Goo inside.

**Comment by madewokherd** [comment]
The MojoShader build fails because mojoshader_opengl.c doesn't include windows.h (_MSC_VER isn't defined in mingw).

**Comment by flibitijibibo** [comment]
I wonder... what happens when you take the `GL/` folder's headers and replace them with the Mesa3D `gl.h` and `glext.h`? If that works then we should probably just update (I think they're 15+ years old?) and remove that MSC_VER block altogether.

**Comment by madewokherd** [comment]
Why don't you use system headers?

**Comment by flibitijibibo** [comment]
I think it's for Visual Studio (at least, glext is). These headers are probably a decade old at least, so maybe it was for something else back then, not sure.

**Comment by madewokherd** [comment]
Yes, it works with updated headers from mesa3d.

**Comment by madewokherd** [comment]
I'm gong to have to add an option to build FNA with a strongname, so it can be installed into the GAC. That's going to require shipping a key in the source. Not sure if I should just use the mono key, or build a new one for this.

It occurs to me that strongnames remove the need to rename the library, at least. Though there's the argument that if FNA has an official strongname, someone might decide to install that to the GAC, and therefore we shouldn't use it.

The ABI libraries will have to use a special key that Mono will map to the appropriate publickeytoken.

**Comment by madewokherd** [comment]
Well, I have hacked things together enough that Wine Mono builds and One Finger Death Punch works without messing with the install (except that it complains about lack of Steam and doesn't exit cleanly). I put all the class libraries in the GAC and used FNA.dll.config to find the native libraries.

Now that I'm looking back at how you did it, I don't understand the Facades directory or why dropping things in there works.

**Comment by madewokherd** [comment]
I'm still not sure why the Facades directory works, but I'm convinced using the GAC is cleaner. Do you want upstream FNA to have the ability to build a version with a strongname that can be installed to the GAC? If so, I may be able to avoid a fork for wine-mono. I don't think there's a need for wine-mono's FNA to have a unique strongname. As long as we're not forking it, strongnames should prevent dll hell.

It turns out that I made a mistake when I updated the headers for MojoShader, and only updated gl.h. That works, but if I also update glext.h the build fails. Replacing the ifdef _MSC_VER with a check for _WIN32 also works.

**Comment by flibitijibibo** [comment]
It sounds we've got a growing TODO list for FNA in wine-mono, so go ahead and fork what you need and rip things up to make it all work; 19.03's about to get tagged anyhow so we've got a whole month to tie everything up in a nice neat bow for when we have everything working all at once.

**Comment by madewokherd** [comment]
WIP branch updated with a working version: https://github.com/madewokherd/wine-mono/tree/fna-wip

**Comment by flibitijibibo** [comment]
Still looking at using built-in features to support image I/O in wine-fna, but as a quick fix in case we need it, SDL_image_compact's Makefile has the same out-of-tree support as Theorafile now:

https://github.com/FNA-XNA/SDL_image_compact/commit/e40c46d4d17b0ae00c3c39ea27a8446673374db4

**Comment by madewokherd** [comment]
I'm declaring this issue fixed now.
