### ISSUE TITLE
TesModManager fail to call AddHostEvidence.

### ISSUE THREAD

**Issue by llde** [madewokherd/wine-mono#46]
Type: System.MissingMethodException
Error message: Method not found: void System.Security.Policy.Evidence.AddHostEvidence<!0>(!!0)
Stack trace:   at (wrapper remoting-invoke-with-check) OblivionModManager.MainForm..ctor()
  at OblivionModManager.Program.Main (System.String[] args) [0x001d3] in <1db7edf1feeb4790a6635f143f44746a>:0 

However AddHostEvidence is present in mono sourcecode.

**Comment by llde** [comment]
The issue is actually in Mono upstream. Opened a report on upstream

**Comment by madewokherd** [comment]
Linking upstream issue here: https://github.com/mono/mono/issues/20840

**Comment by madewokherd** [comment]
It seems like this got stalled upstream, would you like me to review it for wine-mono?

**Comment by llde** [comment]
@madewokherd if you want as a temporary measure, I was planning to resend it after the CI changes complete. It should overal easy to revert it in case

**Comment by madewokherd** [comment]
Thanks, I've pushed your changes. I'll keep an eye on the PR in case something different gets accepted upstream.

**Comment by madewokherd** [comment]
The change is in Wine Mono 6.1.1 / Wine 6.6.
