### ISSUE TITLE
Building in mac os x, possible?

### ISSUE THREAD

**Issue by rlisper** [madewokherd/wine-mono#5]
I trying to build wine-mono by the way passed in README file. But in the build-winemono.sh used mingw that not good choice for os x and I should use other compiler? gcc? In general - what I should do to install wine-mono in mac os x? 

config.log: 
http://paste.lisp.org/display/133681

**Comment by madewokherd** [comment]
mingw-w64 can run on OS X. This should be possible. Closing.
