### ISSUE TITLE
where can I get the sha256 checksum of 4.8.3?

### ISSUE THREAD

**Issue by braindevices** [madewokherd/wine-mono#51]
I only see the wine-mono-4.8.1.msi's checksum in [master branch](https://source.winehq.org/git/wine.git/blob/refs/heads/master:/dlls/appwiz.cpl/addons.c) of wine. Is it possible to post the checksum on release page?

**Comment by madewokherd** [comment]
I can, but I don't know what problem that solves.

**Comment by braindevices** [comment]
@madewokherd to avoid downloading tampered installer. If you can sign it, it will be the best. But sha256 checksum should be good already normally.

**Comment by madewokherd** [comment]
I sent an update to Wine this morning: https://source.winehq.org/patches/data/163555

Normally, I'd do that within a day of making the release, but I had some trouble with this one.

**Comment by braindevices** [comment]
@Mailaender Thanks a lot! But post the checksum on release page should also make it more clear.
