### ISSUE TITLE
why can't I see all the code?

### ISSUE THREAD

**Issue by codeman101** [madewokherd/wine-mono#53]
The license doc makes it seem like most of the code is under some form of the MIT license but the mono and mono-basic directories aren't clickable here on github and cloning the repo gives empty folders. I see that the code is split among licenses but as far as I'm aware all varying licenses allow the code to be seen.

**Comment by madewokherd** [comment]
They're submodules. https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by codeman101** [comment]
Thanks. I just have one other question (I guess follow up question)  that I think falls under the same category (well in a way) Why is this project not included in the download of the wine source code? (Especially with how required it has become to run Windows stuff on wine)

**Comment by madewokherd** [comment]
Wine can still run most applications without .NET support, and even for .NET applications the native runtime is still the more common choice. Even the windowing system is technically an optional dependency for Wine.

I think it's important to the Wine maintainer that all of the Wine source code be carefully curated with all changes reviewed. Bringing in an external project does not allow for this, as we have to continually merge in changes from upstream. Mono in particular keeps bringing in its own dependencies which bloat the wine-mono source code.

**Comment by codeman101** [comment]
Thanks for the explaining. I guess I didn't realize that Wine can understand native Windows .Net binaries. Actually I thought that was the whole reason why wine-mono was created because if one was to install the binary from here https://www.microsoft.com/en-us/download/details.aspx?id=30653 It wouldn't help wine at all even if the program you're trying to get going has .Net as a dependency.

**Comment by codeman101** [comment]
I actually I take part of my previous post back. I completely forgot that wine-mono conflicts with dotnet. (which is the issue I ran into just now) Also for some reason I always thought that the dotnet you get from winetricks was a modified version of the actual on the Microsoft site.

**Comment by codeman101** [comment]
I still have one other question about submodules. In all the examples I've seen the code of the submodule is included in the repo. Why is that not the case here? (since all submodule means is that you included code from another repo)

**Comment by nsivov** [comment]
Submodule means you don't include code from another repo to yours, but instead link this other repo to the main one.

**Comment by codeman101** [comment]
@nsivov Yeah sorry I just ran yarn on a yarn install on a repo and saw that it cloning the submodules. It's very odd thought because based of a video I saw on the subject I thought you import the code from a given commit to your repo.
