### ISSUE TITLE
Update to latest FNA revision

### ISSUE THREAD

**Issue by flibitijibibo** [madewokherd/wine-mono#55]
In addition to the usual stable updates from 19.07, the latest Git revision has some pretty important fixes for some Windows-only XNA games:

https://github.com/FNA-XNA/FNA/commit/c8e7b27a2443e896d0599f09c0fa940d3281c281
https://github.com/FNA-XNA/MojoShader/commit/df8a5c1674e99f6cf0d4d9cb28c138fd217ec543

A good test case for both of these is Lemma:

https://store.steampowered.com/app/300340/Lemma/

Lemma's FNA port, for reference:

https://github.com/etodd/Lemma/pull/6

**Comment by flibitijibibo** [comment]
Another revision that wine-mono cares about:

https://github.com/FNA-XNA/FNA/commit/4931fd23e54635b5279d668c5fe1b7808ef3380b

**Comment by flibitijibibo** [comment]
Poking this thread one more time for 19.09 - this month's release has some fixes that wine-mono in particular cares about, including improved shader support, the ThreadedGLDevice, and performance improvements for both FNA and FAudio.

**Comment by madewokherd** [comment]
Working on this now, should I include any of the commits after 19.09?

**Comment by flibitijibibo** [comment]
FNA has a couple commits that fix multiple vertex buffer bindings with overlapping element usages, while FAudio has a handful of optimizations for the reverb effect. It's been pretty slow this month!

**Comment by madewokherd** [comment]
Updated FNA to 19.09 in Wine Mono 4.9.3.
