### ISSUE TITLE
Strip shipped binaries

### ISSUE THREAD

**Issue by aeikum** [madewokherd/wine-mono#59]
We could save about 70MB by stripping `bin/*.dll` and `lib/*.dll` in the end-user distribution. Extracted from the tarball distribution:

    wine-mono-4.9.3$ du -hsc .
    262M        .
    262M        total
    wine-mono-4.9.3$ for f in bin/*.dll lib/*.dll; do strip $f; done
    wine-mono-4.9.3$ du -hsc .
    191M        .
    191M        total

**Comment by madewokherd** [comment]
This would be cleaner if there were a way to split it into a .pdb file. Then I could just exclude those from the normal targets and archive them separately.

**Comment by mirh** [comment]
Can be closed I guess.
