### ISSUE TITLE
New release with btls?

### ISSUE THREAD

**Issue by Hello71** [madewokherd/wine-mono#61]
Seems like at least Scrivener and StudioTax require TLS 1.2. Firefox is now requiring TLS 1.2, and I think Chrome will be soon, so I think this will become increasingly important.

I see that btls is implemented in master, but it's a fair bit of time and internet usage to download and compile from scratch, so if a full release is too much work, even an interim binary would be helpful.

Thanks!

**Comment by madewokherd** [comment]
I've been waiting for a few things to be in a better state, but none of them are worse than 4.9, so maybe you're right.

**Comment by madewokherd** [comment]
Wine Mono 5.0.0 is out and will be in Wine 4.7.
