### ISSUE TITLE
Mafia III Demo Requires MILCreateEventProxy implementation

### ISSUE THREAD

**Issue by alesliehughes** [madewokherd/wine-mono#66]
When running the Mafia III demo.  It crashes at the start which is caused by MILCreateEventProxy being not implemented.

internal static SafeMILHandle CreateEventProxyWrapper(IInvokable invokable)
....
HRESULT.Check(MILCreateEventProxy(ref epd, out eventProxy));   <-- Crash.

This function is included via the stub.cpp file, which is fine for linux land but we really want to use the eventproxy.cpp for wine which has the implementation.

**Comment by madewokherd** [comment]
This is probably part of the files I wasn't able to compile due to missing WMP SDK headers.

**Comment by alesliehughes** [comment]
Do you have a list of the missing headers?

**Comment by madewokherd** [comment]
No, I'd have to try building them again.

**Comment by rbernon** [comment]
I've got a tree that compiles in https://github.com/rbernon/wpf/tree/bug/18226/v1, but it needs a few wine IDL additions.
