### ISSUE TITLE
macOS testing - using depreciated packages

### ISSUE THREAD

**Issue by Gcenx** [madewokherd/wine-mono#84]
First I’d like to apologize for not noticing this sooner, but the current Winehq macOS wine-devel package would be wine-5.7 not sure if that would cause problems for these tests or not.

https://github.com/madewokherd/wine-mono/blob/bdc4a0f5c32b358ba24872f9b7cc6d9b62ecc9d7/.github/workflows/c-cpp.yml#L120-L122

As you’ll be using this via `brew` and using the latest macOS image maybe using my packages might be better for these tests.

This could be replaced with the following;
```
brew tap gcenx/wine
brew install --cask --no-quarantine gcenx-wine-devel
```
XQuartz is not required, just an FWI I do bundle wine-gecko & wine-mono but reading over I’m not sure this would matter.

**Comment by madewokherd** [comment]
The old version is not ideal. Things will probably work with that version but for testing purposes we want the latest release. @Endle ?

**Comment by Endle** [comment]
I agree with you. Old version wine is sufficient to compile wine-mono. If we want to run the tests, we should use new wine version.
I followed wine wikihttps://wiki.winehq.org/MacOS
I think we could report this outdated issue current brew maintainer, or edit wiki pointing to new brew package 

发自 iPhone 版 Yahoo 邮箱


星期五, 二月 26, 2021, 12:08 下午 于 Esme <notifications@github.com>写道：




The old version is not ideal. Things will probably work with that version but for testing purposes we want the latest release. @Endle ?

**Comment by Gcenx** [comment]
Homebrew won't upgrade there casks unless my packages become the official Winehq packages, but I don’t see this happening as I only support 10.13 or greater.

That’s also why I haven’t edited the wiki, even macports still only provides wine-4.0.4 & wine-devel-4.9 without installing the overlay I maintain.

**Comment by madewokherd** [comment]
I wonder if building wine would make more sense. That would also take care of the potential difference between the latest release and the winetest exe.

**Comment by Gcenx** [comment]
Looking over the CI again it’s not possible that wine64 is being used during the make stage only when running the tests.

It’s definitely possible to compile wine64 along using brew provided dependencies if needed, but that would also increase the CI build time where it would make more sense to then split the macOS testing into its own CI.

As initially mentioned if needed my packages could be used for the latest version of wine-stable/devel/staging, if another option would need to be enabled/disabled to make them more appealing for this just let me know.

**Comment by Endle** [comment]
I think build time is not a big issue - Github Action is quite generous for CI time
However, if we compile wine by ourselves, should we use git version or latest develop release?

**Comment by madewokherd** [comment]
Git version seems simplest.

**Comment by Gcenx** [comment]
True, Github actions does have a rather long allowance unlike Jenkins.

The only concern would be wine at least on macOS has more breakages between releases.

**Comment by Gcenx** [comment]
This was resolved via https://github.com/madewokherd/wine-mono/commit/2b6a1c19ec5486b7d7e5a06bafd8772b0af09339
